openapi: 3.0.1
info:
  title: League Challenges - User Management API
  description: League Challenges - User Management API
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /api/users/{user_id}:
    patch:
      summary: Set new ingame user id

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/player_uuid'
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucessfully patched ingame user id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found or invalid token
  /api/auth/me:
    get:
      description: Get own data
      tags:
        - user
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucessfully returned user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found or invalid token
  /api/auth/login:
    post:
      description: Login into website
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/form_data'
      responses:
        '200':
          description: Sucessfully returned user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '400':
          description: Invalid input
  /api/auth/register:
    post:
      description: Register new account
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/form_data'
      responses:
        '200':
          description: Sucessfully returned mail of registered acc
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    mail:
                      type: string
        '400':
          description: Invalid input
  /api/competitors/:
    get:
      description: List of competitors of user
      tags:
        - competitor
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Sucessfully returned list of competitors
          content:
            application/json:
              schema: 
                type: array
                items:
                  properties:
                    competitor:
                      $ref: '#/components/schemas/Competitor'
  /api/competitors/{competitor}:
      get:
        description: Get specific competitor
        tags:
          - competitor
        parameters:
          - name: token
            in: header
            required: true
            schema:
              type: string
          - name: competitor
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Sucessfully returned token
            content:
              application/json:
                schema:
                  type: array
                  items:
                    properties:
                      competitor:
                        $ref: '#/components/schemas/Competitor'
components:
  schemas:
    User:
      type: object
      properties:
        player_uuid:
          type: string
        username:
          type: string
        mail:
          type: string
        token:
          type: string
    Competitor:
      type: object
      properties:
        player_id: 
          type: string
        username: 
          type: string
    player_uuid:
      type: object
      properties:
        player_uuid:
          type: string
    form_data:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
