"""column competitor ingame name renamed

Revision ID: 0eda52845c93
Revises: b82b20947972
Create Date: 2022-05-16 21:59:29.507705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eda52845c93'
down_revision = 'b82b20947972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('player_name', sa.String(length=255), nullable=False))
    op.drop_column('competitors', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('competitors', 'player_name')
    # ### end Alembic commands ###
