"""removed player name

Revision ID: aca84dcc6d59
Revises: 6e339e30df24
Create Date: 2022-06-12 22:39:33.583110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca84dcc6d59'
down_revision = '6e339e30df24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitors', 'player_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitors', sa.Column('player_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
