version: 1
disable_existing_loggers: false
formatters:
    simple:
        format: ts="%(asctime)s" lvl=%(levelname)s logger=%(name)s %(message)s



handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

root:
    level: INFO
    handlers: [console]
    propagate: yes

loggers:
    player_api:
        level: DEBUG
        handlers: [console]
        propagate: no
