# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import player_api.playerImportRequest_pb2 as playerImportRequest__pb2


class ImporterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.import_player = channel.unary_stream(
            "/Importer/import_player",
            request_serializer=playerImportRequest__pb2.ImportRequest.SerializeToString,
            response_deserializer=playerImportRequest__pb2.ImportReply.FromString,
        )


class ImporterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def import_player(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ImporterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "import_player": grpc.unary_stream_rpc_method_handler(
            servicer.import_player,
            request_deserializer=playerImportRequest__pb2.ImportRequest.FromString,
            response_serializer=playerImportRequest__pb2.ImportReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Importer", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Importer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def import_player(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/Importer/import_player",
            playerImportRequest__pb2.ImportRequest.SerializeToString,
            playerImportRequest__pb2.ImportReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
